// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClientConnectedArgs {}

impl From<ClientConnectedArgs> for super::Reducer {
    fn from(args: ClientConnectedArgs) -> Self {
        Self::ClientConnected
    }
}

impl __sdk::InModule for ClientConnectedArgs {
    type Module = super::RemoteModule;
}

pub struct ClientConnectedCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `client_connected`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait client_connected {
    /// Request that the remote module invoke the reducer `client_connected` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_client_connected`] callbacks.
    fn client_connected(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `client_connected`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ClientConnectedCallbackId`] can be passed to [`Self::remove_on_client_connected`]
    /// to cancel the callback.
    fn on_client_connected(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ClientConnectedCallbackId;
    /// Cancel a callback previously registered by [`Self::on_client_connected`],
    /// causing it not to run in the future.
    fn remove_on_client_connected(&self, callback: ClientConnectedCallbackId);
}

impl client_connected for super::RemoteReducers {
    fn client_connected(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("client_connected", ClientConnectedArgs {})
    }
    fn on_client_connected(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ClientConnectedCallbackId {
        ClientConnectedCallbackId(self.imp.on_reducer(
            "client_connected",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ClientConnected {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_client_connected(&self, callback: ClientConnectedCallbackId) {
        self.imp.remove_on_reducer("client_connected", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `client_connected`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_client_connected {
    /// Set the call-reducer flags for the reducer `client_connected` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn client_connected(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_client_connected for super::SetReducerFlags {
    fn client_connected(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("client_connected", flags);
    }
}
